# Generated by Django 5.0.3 on 2024-03-29 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('seller_email', models.EmailField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='A brief name for your item, for example "Electric kettle"', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('donation', models.PositiveSmallIntegerField(help_text='The percentage of the value of your item to donate to 11th/9th Cambridge Scout Group', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
    ]
