# Generated by Django 5.0.3 on 2024-04-05 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutsalesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='donation',
            field=models.PositiveSmallIntegerField(default=40, help_text='The percentage of the value of your item (minimum 25%) to donate to 11th/9th Cambridge Scout Group', validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
