# Generated by Django 5.0.3 on 2024-04-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutsalesapp', '0002_alter_item_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner_token',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
