# Generated by Django 5.0.3 on 2024-04-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutsalesapp', '0004_alter_item_owner_token_transaction_item_sold_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
